# Generated by Django 5.1.1 on 2024-10-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_tg_nickname_user_tg_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_name',
            field=models.CharField(blank=True, help_text='Укажите свой Телеграм ник', max_length=50, null=True, verbose_name='Телеграм ник'),
        ),
    ]
