# Generated by Django 5.1.1 on 2024-10-01 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, help_text='Укажите место, где необходимо выполнять привычку', max_length=255, null=True, verbose_name='Место привычки')),
                ('time', models.DateTimeField(blank=True, help_text='Укажите время, когда необходимо выполнять привычку', null=True, verbose_name='Время выполнения')),
                ('action', models.CharField(help_text='Укажите действие, которое представляет собой привычка', max_length=255, verbose_name='Действие')),
                ('sign_nice_habit', models.BooleanField(blank=True, default=False, help_text='Привычка, которую можно привязать к выполнению полезной привычки', null=True, verbose_name='Признак приятной привычки')),
                ('periodicity', models.CharField(blank=True, choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно')], help_text='Укажите периодичность выполнения привычки в днях', max_length=255, null=True, verbose_name='Периодичность выполнения')),
                ('reward', models.CharField(blank=True, help_text='Укажите награду за выполнение привычки', max_length=255, null=True, verbose_name='Вознаграждение')),
                ('time_to_complete', models.PositiveIntegerField(blank=True, default=180, help_text='Укажите время для выполнения привычки в минутах', null=True, verbose_name='Время для выполнения привычки')),
                ('is_published', models.BooleanField(blank=True, default=False, help_text='Отметьте, если привычка доступна для других пользователей', null=True, verbose_name='Признак публичности')),
                ('related_habit', models.ForeignKey(blank=True, help_text='Привычка, которая связана с другой привычкой, указывать для полезных привычек, но не для приятных', null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Связанная привычка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
