# Generated by Django 5.1.1 on 2024-09-27 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HabitCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название категории привычек', max_length=255, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, help_text='Укажите описание категории привычек', null=True, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория привычек',
                'verbose_name_plural': 'Категории привычек',
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата выполнения')),
                ('completed', models.BooleanField(default=False, help_text='Отметьте, если привычка выполнена', verbose_name='Статус выполнения')),
            ],
            options={
                'verbose_name': 'Лог выполнения привычки',
                'verbose_name_plural': 'Логи выполнения привычек',
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(help_text='Укажите место, где необходимо выполнять привычку', max_length=255, verbose_name='Место привычки')),
                ('time', models.DateTimeField(help_text='Укажите время, когда необходимо выполнять привычку', verbose_name='Время выполнения')),
                ('action', models.CharField(help_text='Укажите действие, которое представляет собой привычка', max_length=255, verbose_name='Действие')),
                ('sign_nice_habit', models.BooleanField(blank=True, default=False, help_text='Привычка, которую можно привязать к выполнению полезной привычки', null=True, verbose_name='Признак приятной привычки')),
                ('periodicity', models.PositiveIntegerField(default=1, help_text='Укажите периодичность выполнения привычки в днях', verbose_name='Периодичность выполнения')),
                ('reward', models.CharField(blank=True, help_text='Укажите награду за выполнение привычки', max_length=255, null=True, verbose_name='Вознаграждение')),
                ('time_to_complete', models.PositiveIntegerField(default=180, help_text='Укажите время для выполнения привычки в минутах', verbose_name='Время для выполнения привычки')),
                ('is_public', models.BooleanField(blank=True, default=False, help_text='Отметьте, если привычка доступна для других пользователей', null=True, verbose_name='Признак публичности')),
                ('related_habit', models.ForeignKey(blank=True, help_text='Привычка, которая связана с другой привычкой, указывать для полезных привычек, но не для приятных', null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
