# Generated by Django 5.1.1 on 2024-10-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.PositiveIntegerField(blank=True, default=168, help_text='Укажите периодичность выполнения привычки в часах (не более 168 часов-раз в неделю)', max_length=255, null=True, verbose_name='Периодичность выполнения'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time_to_complete',
            field=models.PositiveIntegerField(blank=True, default=120, help_text='Укажите время для выполнения привычки в секундах, не более 120 секунд', null=True, verbose_name='Время для выполнения привычки'),
        ),
    ]
