# Generated by Django 5.1.1 on 2024-09-27 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='habit',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Укажите категорию привычки', null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habitcategory', verbose_name='Категория привычки'),
        ),
        migrations.AddField(
            model_name='habitlog',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='habits.habit'),
        ),
        migrations.AddField(
            model_name='habitlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
