# Generated by Django 5.1.1 on 2024-10-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(blank=True, help_text='Укажите время, когда необходимо выполнять привычку', null=True, verbose_name='Время выполнения'),
        ),
    ]
