# Generated by Django 5.1.1 on 2024-10-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_periodicity_alter_habit_time_to_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.PositiveIntegerField(blank=True, default=168, help_text='Укажите периодичность выполнения привычки в часах (не более 168 часов-не реже 1 раза в неделю)', null=True, verbose_name='Периодичность выполнения'),
        ),
    ]
