# Generated by Django 5.1.1 on 2024-10-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.PositiveIntegerField(blank=True, help_text='Укажите периодичность выполнения привычки в часах (не более 168 часов-не реже 1 раза в неделю)', null=True, verbose_name='Периодичность выполнения'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time_to_complete',
            field=models.PositiveIntegerField(blank=True, help_text='Укажите время для выполнения привычки в секундах, не более 120 секунд', null=True, verbose_name='Время для выполнения привычки'),
        ),
    ]
