# Generated by Django 5.1.1 on 2024-10-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_periodicity_alter_habit_time_to_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.PositiveIntegerField(blank=True, help_text='Укажите количество выполнений привычки в неделю (не реже 1 раза в неделю)', null=True, verbose_name='Периодичность выполнения'),
        ),
    ]
